# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_recipe_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1379, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.menu_button.setGeometry(QtCore.QRect(0, 0, 141, 61))
        self.menu_button.setObjectName("menu_button")
        self.add_recipe_widget = QtWidgets.QWidget(self.centralwidget)
        self.add_recipe_widget.setGeometry(QtCore.QRect(490, 290, 301, 221))
        self.add_recipe_widget.setObjectName("add_recipe_widget")
        self.pushButton = QtWidgets.QPushButton(self.add_recipe_widget)
        self.pushButton.setGeometry(QtCore.QRect(70, 60, 151, 41))
        self.pushButton.setObjectName("pushButton")
        self.add_pecipe_product_label = QtWidgets.QLabel(self.add_recipe_widget)
        self.add_pecipe_product_label.setGeometry(QtCore.QRect(80, 110, 141, 31))
        self.add_pecipe_product_label.setObjectName("add_pecipe_product_label")
        self.add_recipe_line_edit = QtWidgets.QLineEdit(self.add_recipe_widget)
        self.add_recipe_line_edit.setGeometry(QtCore.QRect(70, 0, 151, 41))
        self.add_recipe_line_edit.setObjectName("add_recipe_line_edit")
        self.add_recipe_save_button = QtWidgets.QPushButton(self.add_recipe_widget)
        self.add_recipe_save_button.setGeometry(QtCore.QRect(70, 150, 151, 41))
        self.add_recipe_save_button.setObjectName("add_recipe_save_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_button.setText(_translate("MainWindow", "╨Ь╨╡╨╜╤О"))
        self.pushButton.setText(_translate("MainWindow", "╨Ф╨╛╨▒╨░╨▓╨╕╤В╤М ╨┐╤А╨╛╨┤╤Г╨║╤В"))
        self.add_pecipe_product_label.setText(_translate("MainWindow", "╨Э╨░╨╖╨▓╨░╨╜╨╕╨╡"))
        self.add_recipe_line_edit.setText(_translate("MainWindow", "╨Э╨░╨╖╨▓╨░╨╜╨╕╨╡"))
        self.add_recipe_save_button.setText(_translate("MainWindow", "╨б╨╛╤Е╤А╨░╨╜╨╕╤В╤М"))
