from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class RegForm(QMainWindow):
    def __init__(self, mainwindow):
        super().__init__()
        self.setupUi(mainwindow)

    def setupUi(self, mainwindow):
        mainwindow.setObjectName("MainWindow")
        mainwindow.resize(1377, 865)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.reg_form_back_button = QtWidgets.QPushButton(self.centralwidget)
        self.reg_form_back_button.setGeometry(QtCore.QRect(0, 0, 121, 61))
        self.reg_form_back_button.setObjectName("reg_form_back_button")
        self.person_name_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.person_name_line_edit.setGeometry(QtCore.QRect(530, 210, 331, 41))
        self.person_name_line_edit.setObjectName("person_name_line_edit")
        self.person_lastname_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.person_lastname_line_edit.setGeometry(QtCore.QRect(530, 260, 331, 41))
        self.person_lastname_line_edit.setObjectName("person_lastname_line_edit")
        self.person_login_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.person_login_line_edit.setGeometry(QtCore.QRect(530, 310, 331, 41))
        self.person_login_line_edit.setObjectName("person_login_line_edit")
        self.person_height_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.person_height_line_edit.setGeometry(QtCore.QRect(530, 410, 331, 41))
        self.person_height_line_edit.setObjectName("person_height_line_edit")
        self.person_weight_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.person_weight_line_edit.setGeometry(QtCore.QRect(530, 460, 331, 41))
        self.person_weight_line_edit.setObjectName("person_weight_line_edit")
        self.person_age_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.person_age_line_edit.setGeometry(QtCore.QRect(530, 510, 331, 41))
        self.person_age_line_edit.setObjectName("person_age_line_edit")
        self.person_password_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.person_password_line_edit.setGeometry(QtCore.QRect(530, 360, 331, 41))
        self.person_password_line_edit.setObjectName("person_password_line_edit")
        self.reg_confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.reg_confirm_button.setGeometry(QtCore.QRect(630, 620, 141, 71))
        self.reg_confirm_button.setObjectName("reg_confirm_button")
        self.person_sex_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.person_sex_combobox.setGeometry(QtCore.QRect(530, 560, 331, 41))
        self.person_sex_combobox.setObjectName("person_sex_combobox")
        self.person_sex_combobox.addItem("")
        self.person_sex_combobox.addItem("")
        mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.setCentralWidget(self.centralwidget)
